name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install
              run: yarn
            - name: Test
              run: yarn test:coverage --ci
            - name: Codecov
              uses: codecov/codecov-action@v1.5.0
