name: NPM Publish

on:
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
            - uses: pnpm/action-setup@v4.1.0
              name: Install pnpm
            - name: Install Dependencies
              run: pnpm install
            - run: pnpm build
            - run: pnpm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
            - run: pnpm publish --no-git-checks
